update@20260708

diff --git a/package/network/services/dropbear/files/dropbear.init b/package/network/services/dropbear/files/dropbear.init
--- a/package/network/services/dropbear/files/dropbear.init
+++ b/package/network/services/dropbear/files/dropbear.init
@@ -18,14 +18,9 @@ dumb_stat() { ls -Ldln "$1" | tr -s '\t ' ' ' ; }
 stat_perm()  { real_stat -c '%A' "$1" || dumb_stat "$1" | cut -d ' ' -f 1 ; }
 stat_owner() { real_stat -c '%u' "$1" || dumb_stat "$1" | cut -d ' ' -f 3 ; }
 
-db_key_quiet() { dropbearkey "$@" </dev/null >/dev/null 2>&1 ; }
-db_key_types_int() {
-	dropbearkey -h </dev/null 2>&1 \
-	| sed -En '/^\s*-t/,/^\s*-/p' \
-	| sed -En '/^\s*-/n;p'
-}
-db_key_types() {
-	normalize_list "$(db_key_types_int)"
+_dropbearkey()
+{
+	/usr/bin/dropbearkey "$@" </dev/null >/dev/null 2>&1
 }
 
 # $1 - file name (host key or config)
@@ -48,7 +43,7 @@ file_verify()
 	[ -z "$2" ] || return 0
 	# checking file contents (finally)
 	[ -s "$1" ] || return 4
-	db_key_quiet -y -f "$1" || return 5
+	_dropbearkey -y -f "$1" || return 5
 	return 0
 }
 
@@ -84,21 +79,14 @@ hk_config()
 # $1 - host key file name
 hk_config__keyfile() { hk_config keyfile "$1" ; }
 
+ktype_all='ed25519 ecdsa rsa'
+
 hk_generate_as_needed()
 {
-	local hk_cfg_dir ktype_all kgen ktype kfile hk_tmp_dir
+	local hk_cfg_dir kgen ktype kfile hk_tmp_dir
 	hk_cfg_dir='/etc/dropbear'
 
 	[ -d "${hk_cfg_dir}" ] || mkdir -p "${hk_cfg_dir}"
-
-	# don't hardcode supported algorithm list until things go wrong
-	ktype_all=$(db_key_types)
-	[ -n "${ktype_all}" ] || {
-		logger -t "${NAME}" -p daemon.warn \
-		  "unable to correctly retrieve supported hostkey algorithms!"
-
-		ktype_all='rsa ecdsa ed25519'
-	}
 
 	kgen=
 	for ktype in ${ktype_all} ; do
@@ -106,10 +94,7 @@ hk_generate_as_needed()
 
 		if file_verify "${kfile}" ; then continue ; fi
 
-		# cleanup empty files (if any)
-		[ -s "${kfile}" ] || rm -f "${kfile}"
-
-		kgen="${kgen} ${ktype}"
+		kgen="${kgen}${kgen:+ }${ktype}"
 	done
 
 	# all keys are sane?
@@ -118,27 +103,28 @@ hk_generate_as_needed()
 	hk_tmp_dir=$(mktemp -d)
 	# system in bad state?
 	[ -n "${hk_tmp_dir}" ] || return 1
+
 	chmod 0700 "${hk_tmp_dir}"
 
 	for ktype in ${kgen} ; do
 		kfile="${hk_tmp_dir}/dropbear_${ktype}_host_key"
 
-		if ! db_key_quiet -t "${ktype}" -f "${kfile}" ; then
+		if ! _dropbearkey -t ${ktype} -f "${kfile}" ; then
 			# unsupported key type
-			rm -f "${kfile}" "${kfile}.pub"
+			rm -f "${kfile}"
 			continue
 		fi
 
 		chmod 0600 "${kfile}"
-		# unused file
-		rm -f "${kfile}.pub"
 	done
 
 	kgen=
 	for ktype in ${ktype_all} ; do
 		kfile="${hk_tmp_dir}/dropbear_${ktype}_host_key"
+
 		[ -s "${kfile}" ] || continue
-		kgen="${kgen} ${ktype}"
+
+		kgen="${kgen}${kgen:+ }${ktype}"
 	done
 
 	if [ -n "${kgen}" ] ; then
@@ -150,6 +136,13 @@ hk_generate_as_needed()
 	fi
 
 	rm -rf "${hk_tmp_dir}"
+
+	# cleanup empty files
+	for ktype in ${ktype_all} ; do
+		kfile="${hk_cfg_dir}/dropbear_${ktype}_host_key"
+
+		[ -s "${kfile}" ] || rm -f "${kfile}"
+	done
 }
 
 # $1 - list with whitespace-separated elements
@@ -183,7 +176,6 @@ validate_section_dropbear()
 		'Port:port:22' \
 		'SSHKeepAlive:uinteger:300' \
 		'IdleTimeout:uinteger:0' \
-		'MaxSessionDuration:uinteger:0' \
 		'MaxAuthTries:uinteger:3' \
 		'RecvWindowSize:uinteger:0' \
 		'LocalPortForward:bool:1' \
@@ -344,7 +336,6 @@ dropbear_instance()
 	fi
 	[ -n "${BannerFile}" ] && procd_append_param command -b "${BannerFile}"
 	[ "${IdleTimeout}" -ne 0 ] && procd_append_param command -I "${IdleTimeout}"
-	[ "${MaxSessionDuration}" -ne 0 ] && procd_append_param command -M "${MaxSessionDuration}"
 	[ "${SSHKeepAlive}" -ne 0 ] && procd_append_param command -K "${SSHKeepAlive}"
 	[ "${MaxAuthTries}" -ne 0 ] && procd_append_param command -T "${MaxAuthTries}"
 	[ "${RecvWindowSize}" -gt 0 ] && {
